apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nephro-uploads
  labels:
    app.kubernetes.io/name: nephro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
