# Analyse SonarQube (scanner Node) — l’URL et le token viennent de withSonarQubeEnv (Jenkins)
sonar.projectKey=kidneycare-frontend
sonar.projectName=KidneyCare Frontend

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/coverage/**,**/public/**
sonar.coverage.exclusions=**/*.spec.ts,**/main.ts,**/polyfills*.js
