apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultation
  labels:
    app.kubernetes.io/name: consultation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: consultation
  template:
    metadata:
      labels:
        app.kubernetes.io/name: consultation
    spec:
      containers:
        - name: consultation
          image: kidneycare/consultation:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/nep?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kidneycare-secrets
                  key: mysql-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kidneycare-secrets
                  key: mysql-password
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka:8761/eureka
            - name: EUREKA_INSTANCE_HOSTNAME
              value: consultation
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://keycloak:8080/realms/kidneyCare-realm
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: http://keycloak:8080/realms/kidneyCare-realm/protocol/openid-connect/certs
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: http://keycloak:8080
          readinessProbe:
            httpGet:
              path: /projet/actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /projet/actuator/health
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 20
