spring.application.name=projetparametrevital
server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/vital_params?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Format date
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=UTC

# Config server (disabled)
spring.config.import=optional:configserver:

# Eureka
eureka.client.enabled=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/realms/kidneyCare-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8080/realms/kidneyCare-realm/protocol/openid-connect/certs}
