# Dev / Minikube uniquement : remplace par SealedSecrets / ExternalSecrets en prod.
apiVersion: v1
kind: Secret
metadata:
  name: kidneycare-secrets
type: Opaque
stringData:
  mysql-root-password: "root"
  mysql-user: "nephro_user"
  mysql-password: "nephro_password"
  mysql-database: "nep"
  keycloak-admin: "admin"
  keycloak-admin-password: "admin"
