spring.application.name=eureka-server
server.port=8761
# Eureka server ne s'enregistre pas et ne récupère pas le registre
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost

# Monitoring (Actuator + Prometheus)
management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
